zookeeper:
  image: sunside/zookeeper
  container_name: zookeeper
  ports: 
    - "49181:2181"

nimbus:
  image: sunside/storm-nimbus
  container_name: storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
  environment: 
    - "ZOOKEEPER_ADDRESS=zookeeper"

supervisor:
  image: sunside/storm-supervisor
  container_name: storm-supervisor
  ports:
    - "8000"
  environment:
    - "NIMBUS_ADDRESS=storm-nimbus"
    - "ZOOKEEPER_ADDRESS=zookeeper"

ui:
  image: sunside/storm-ui
  container_name: storm-ui
  ports:
    - "49080:8080"
  environment:
    - "NIMBUS_ADDRESS=storm-nimbus"
    - "ZOOKEEPER_ADDRESS=zookeeper"
